USE `Tarico_yarn_warehouse`;

insert into item (item_id, category_name, price, total_quantity) values (1, 'Knitting Needles', 28.49, 19);
insert into item (item_id, category_name, price, total_quantity) values (2, 'Yarn', 71.5, 47);
insert into item (item_id, category_name, price, total_quantity) values (3, 'Knitting Needles', 44.57, 24);
insert into item (item_id, category_name, price, total_quantity) values (4, 'Knitting Needles', 30.78, 13);
insert into item (item_id, category_name, price, total_quantity) values (5, 'Knitting Needles', 21.36, 14);
insert into item (item_id, category_name, price, total_quantity) values (6, 'Yarn', 92.66, 14);
insert into item (item_id, category_name, price, total_quantity) values (7, 'Yarn', 29.74, 19);
insert into item (item_id, category_name, price, total_quantity) values (8, 'Yarn', 24.62, 28);
insert into item (item_id, category_name, price, total_quantity) values (9, 'Knitting Needles', 34.2, 27);
insert into item (item_id, category_name, price, total_quantity) values (10, 'Yarn', 82.03, 50);
insert into item (item_id, category_name, price, total_quantity) values (11, 'Knitting Needles', 89.34, 31);
insert into item (item_id, category_name, price, total_quantity) values (12, 'Yarn', 42.95, 34);
insert into item (item_id, category_name, price, total_quantity) values (13, 'Knitting Needles', 44.27, 38);
insert into item (item_id, category_name, price, total_quantity) values (14, 'Knitting Needles', 87.42, 9);
insert into item (item_id, category_name, price, total_quantity) values (15, 'Knitting Needles', 17.25, 21);
insert into item (item_id, category_name, price, total_quantity) values (16, 'Knitting Needles', 72.14, 9);
insert into item (item_id, category_name, price, total_quantity) values (17, 'Yarn', 47.08, 44);
insert into item (item_id, category_name, price, total_quantity) values (18, 'Knitting Needles', 53.74, 45);
insert into item (item_id, category_name, price, total_quantity) values (19, 'Knitting Needles', 41.94, 39);
insert into item (item_id, category_name, price, total_quantity) values (20, 'Yarn', 21.02, 8);
insert into item (item_id, category_name, price, total_quantity) values (21, 'Knitting Needles', 84.47, 23);
insert into item (item_id, category_name, price, total_quantity) values (22, 'Yarn', 21.8, 43);
insert into item (item_id, category_name, price, total_quantity) values (23, 'Knitting Needles', 39.65, 28);
insert into item (item_id, category_name, price, total_quantity) values (24, 'Yarn', 5.58, 45);
insert into item (item_id, category_name, price, total_quantity) values (25, 'Knitting Needles', 79.89, 12);
insert into item (item_id, category_name, price, total_quantity) values (26, 'Knitting Needles', 78.01, 9);
insert into item (item_id, category_name, price, total_quantity) values (27, 'Knitting Needles', 14.32, 2);
insert into item (item_id, category_name, price, total_quantity) values (28, 'Knitting Needles', 76.9, 24);
insert into item (item_id, category_name, price, total_quantity) values (29, 'Knitting Needles', 82.01, 2);
insert into item (item_id, category_name, price, total_quantity) values (30, 'Knitting Needles', 33.31, 10);
insert into item (item_id, category_name, price, total_quantity) values (31, 'Yarn', 75.83, 9);
insert into item (item_id, category_name, price, total_quantity) values (32, 'Knitting Needles', 7.98, 43);
insert into item (item_id, category_name, price, total_quantity) values (33, 'Knitting Needles', 26.9, 45);
insert into item (item_id, category_name, price, total_quantity) values (34, 'Knitting Needles', 58.77, 11);
insert into item (item_id, category_name, price, total_quantity) values (35, 'Yarn', 46.71, 10);
insert into item (item_id, category_name, price, total_quantity) values (36, 'Yarn', 76.74, 21);
insert into item (item_id, category_name, price, total_quantity) values (37, 'Yarn', 39.17, 17);
insert into item (item_id, category_name, price, total_quantity) values (38, 'Yarn', 84.75, 17);
insert into item (item_id, category_name, price, total_quantity) values (39, 'Yarn', 75.79, 36);
insert into item (item_id, category_name, price, total_quantity) values (40, 'Yarn', 5.0, 4);
insert into item (item_id, category_name, price, total_quantity) values (41, 'Yarn', 19.44, 37);
insert into item (item_id, category_name, price, total_quantity) values (42, 'Knitting Needles', 36.82, 30);
insert into item (item_id, category_name, price, total_quantity) values (43, 'Knitting Needles', 29.22, 11);
insert into item (item_id, category_name, price, total_quantity) values (44, 'Yarn', 85.7, 10);
insert into item (item_id, category_name, price, total_quantity) values (45, 'Yarn', 37.21, 29);
insert into item (item_id, category_name, price, total_quantity) values (46, 'Knitting Needles', 24.59, 32);
insert into item (item_id, category_name, price, total_quantity) values (47, 'Knitting Needles', 69.1, 14);
insert into item (item_id, category_name, price, total_quantity) values (48, 'Yarn', 18.59, 29);
insert into item (item_id, category_name, price, total_quantity) values (49, 'Yarn', 6.02, 19);
insert into item (item_id, category_name, price, total_quantity) values (50, 'Knitting Needles', 1.72, 33);
insert into item (item_id, category_name, price, total_quantity) values (51, 'Yarn', 67.34, 9);
insert into item (item_id, category_name, price, total_quantity) values (52, 'Yarn', 37.42, 36);
insert into item (item_id, category_name, price, total_quantity) values (53, 'Yarn', 10.98, 26);
insert into item (item_id, category_name, price, total_quantity) values (54, 'Knitting Needles', 92.17, 18);
insert into item (item_id, category_name, price, total_quantity) values (55, 'Knitting Needles', 19.24, 20);
insert into item (item_id, category_name, price, total_quantity) values (56, 'Knitting Needles', 94.66, 37);
insert into item (item_id, category_name, price, total_quantity) values (57, 'Yarn', 26.88, 2);
insert into item (item_id, category_name, price, total_quantity) values (58, 'Knitting Needles', 40.8, 46);
insert into item (item_id, category_name, price, total_quantity) values (59, 'Yarn', 81.05, 10);
insert into item (item_id, category_name, price, total_quantity) values (60, 'Knitting Needles', 24.29, 15);
insert into item (item_id, category_name, price, total_quantity) values (61, 'Knitting Needles', 20.28, 3);
insert into item (item_id, category_name, price, total_quantity) values (62, 'Yarn', 74.45, 15);
insert into item (item_id, category_name, price, total_quantity) values (63, 'Yarn', 27.54, 17);
insert into item (item_id, category_name, price, total_quantity) values (64, 'Yarn', 39.49, 50);
insert into item (item_id, category_name, price, total_quantity) values (65, 'Yarn', 52.9, 19);
insert into item (item_id, category_name, price, total_quantity) values (66, 'Knitting Needles', 59.43, 48);
insert into item (item_id, category_name, price, total_quantity) values (67, 'Yarn', 90.17, 20);
insert into item (item_id, category_name, price, total_quantity) values (68, 'Knitting Needles', 31.24, 24);
insert into item (item_id, category_name, price, total_quantity) values (69, 'Knitting Needles', 15.42, 48);
insert into item (item_id, category_name, price, total_quantity) values (70, 'Knitting Needles', 60.66, 13);
insert into item (item_id, category_name, price, total_quantity) values (71, 'Yarn', 75.59, 34);
insert into item (item_id, category_name, price, total_quantity) values (72, 'Yarn', 51.76, 25);
insert into item (item_id, category_name, price, total_quantity) values (73, 'Knitting Needles', 3.13, 7);
insert into item (item_id, category_name, price, total_quantity) values (74, 'Yarn', 64.61, 2);
insert into item (item_id, category_name, price, total_quantity) values (75, 'Knitting Needles', 95.65, 13);
insert into item (item_id, category_name, price, total_quantity) values (76, 'Knitting Needles', 65.8, 31);
insert into item (item_id, category_name, price, total_quantity) values (77, 'Knitting Needles', 5.21, 7);
insert into item (item_id, category_name, price, total_quantity) values (78, 'Yarn', 15.52, 29);
insert into item (item_id, category_name, price, total_quantity) values (79, 'Yarn', 84.11, 42);
insert into item (item_id, category_name, price, total_quantity) values (80, 'Knitting Needles', 47.44, 2);
insert into item (item_id, category_name, price, total_quantity) values (81, 'Yarn', 37.39, 38);
insert into item (item_id, category_name, price, total_quantity) values (82, 'Yarn', 49.73, 23);
insert into item (item_id, category_name, price, total_quantity) values (83, 'Knitting Needles', 47.19, 35);
insert into item (item_id, category_name, price, total_quantity) values (84, 'Knitting Needles', 24.53, 48);
insert into item (item_id, category_name, price, total_quantity) values (85, 'Yarn', 15.3, 11);
insert into item (item_id, category_name, price, total_quantity) values (86, 'Yarn', 23.92, 9);
insert into item (item_id, category_name, price, total_quantity) values (87, 'Knitting Needles', 80.19, 25);